:ruby: ree187
# Production
:application: nucleus
:user: rails
:deploy_to: /var/www/apps/nucleus
:domain: nucleusdemo.com
:domain_aliases:
  - demo.get-nucleus.com
  - www.nucleusdemo.com

:repository: git@github.com:electricgraffitti/nucleus.git
:branch: v3

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
:app_symlinks:
 - assets
 - link_avatars
 - pids
 - assets
 - reports
 - attachments
 - comment_attachments
 - avatars
 - videos
#
# Use :local_config to copy directories straight from your local project directory
# to the server: these are files that you don't have/want in scm.
:local_config:
 - config/database.yml
 - config/app_config.yml
#
# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config

# After specifying a gem with config.gem, run 'rake moonshine:gems'
# to update config/gems.yml. If the gem depends on native packages, 
# tell Moonshine here:
:apt_gems:
  :paperclip:
    - imagemagick
  # :rmagick:
  #   - imagemagick
  #   - libmagickcore-dev
  #   - libmagickwand-dev
  # :mini_magick:
  #   - imagemagick
  #   - libmagickcore-dev
  #   - libmagickwand-dev

:rubygems:
  :sources:
    - http://gemcutter.org
    - http://gems.rubyforge.org
    - http://gems.github.com

# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:passenger:
  :max_pool_size: 3
  :use_global_queue: true
  :version: 2.2.15
:mysql:
  :innodb_buffer_pool_size: 128M
